<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-10 12:30
=======
# Generated by Django 6.0.5 on 2026-05-09 09:15
>>>>>>> origin

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('incident_id', models.CharField(max_length=255)),
=======
                ('incident_id', models.UUIDField()),
>>>>>>> origin
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('storage_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
