# Generated by Django 6.0.5 on 2026-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='department_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
