# Generated by Django 6.0.5 on 2026-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='department',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='incident_id',
            field=models.UUIDField(),
        ),
    ]
