# Generated by Django 6.0.5 on 2026-05-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_email_department_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
