# Generated by Django 6.0.5 on 2026-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reporter_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('urgent', 'Urgent')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_id', models.IntegerField()),
                ('actor_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
